### ISSUE TITLE
Cant integrate ruff with doom emacs: cant see any ruff errors

### ISSUE THREAD

**Issue by HappyCthulhu** [erickgnavar/flymake-ruff#12] opened 2023-12-22 10:03 UTC
Hi! Im new to emacs, but im very obsessed with idea integrate ruff to it.

Here's what I did for the setup:

1. I added the following code to config.el:
```
(use-package flymake-ruff
  :ensure t
  :hook (python-mode . flymake-ruff-load))
```

2. I added to packages.el:
```
(package! flymake-ruff)
```

I restarted doom emacs. Of course, Ruff is present in the PATH.
However, I don't see any Ruff errors in the Python code. What am I doing wrong? The only confirmation of the plugin's work: after pressing M-x, I see the command flymake-ruff-load.

Enviropment:
```
[I] valera@t-t14 ~> emacs --version
GNU Emacs 29.1
valera@t-t14
OS: Manjaro Linux x86_64
Kernel: 6.1.62-1-MANJARO
WM: i3
```

I would be grateful for a response! Sorry in advance if the question is silly.

**Comment by erickgnavar** [comment] 2024-01-13 14:45
There was a bug, it was fixed by 8fbc83b, the problem was only for buffers that don't belong to a project

**Closed by erickgnavar** 2024-01-13 14:45 UTC

**Comment by artpelling** [comment] 2025-09-23 13:11
I am still facing this issue. Having the same setup and `flymake-ruff-load` just does nothing...

**Comment by erickgnavar** [comment] 2025-09-23 15:40
Hi, any chance you can share your config and emacs version so I can try to reproduce the error?

**Comment by artpelling** [comment] 2025-09-23 16:20
Sure! My config is pretty similar to @HappyCthulhu, added `flymake-ruff` to `package.el` and adding the same lines to `config.el`. I tried both `MELPA` and adding the repo. 

Ruff 0.13.1 (installed via `uv tool` and in `PATH`).

Doom info:
```shell
generated  Sep 23, 2025 18:14:00
system     Ubuntu 24.04.3 LTS Linux 6.8.0-83-generic x86_64 x
emacs      29.3 EMACSDIR=~/.config/emacs/ EMACS=/usr/bin/emacs
doom       3.0.0-pre PROFILE=_default@0 HEAD -> master ba1dca322 2024-12-05 16:39:23
           -0500 ~/.doom.d/
shell      /usr/bin/zsh
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG
           JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES
           NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS
           TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3
           ZLIB
traits     gui server-running envvar-file
modules    :config use-package :completion (company +childframe) (vertico +icons) :ui
           doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all
           +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold
           snippets :emacs dired electric vc :checkers (syntax +childframe) :tools
           biblio (eval +overlay) lookup (lsp +eglot +peek) (magit +forge) pdf
           tree-sitter :lang (cc +lsp) emacs-lisp (latex +cdlatex +fold +lsp) markdown
           (org +cdlatex +jupyter +pretty) (python +lsp +tree-sitter) (rust +lsp
           +tree-sitter) sh :app calendar :config (default +smartparens)
packages   (org-caldav) (skeletor) (pipenv :disable t) (py-prof :recipe (:host github
           :repo GioBo/py-prof)) (latex-extra :recipe (:host github :repo
           berhoel/latex-extra)) (undo-tree) (all-the-icons) (copilot :recipe (:host
           github :repo copilot-emacs/copilot.el :files (*.el))) (flymake-ruff) (jinx)

```

**Comment by erickgnavar** [comment] 2025-09-28 18:32
Hi, can you check these things?
- `C-h m` and check if `flymake` is enabled
- `M :` (eval expression) and type `(flymake-running-backends)` and share the output
- `M :` and type `(executable-find "ruff")` and share the output

**Comment by artpelling** [comment] 2025-09-29 08:28
Thanks for looking into this. I've noticed that `flymake` was not running as expected. When looking into it, I found a [PR for `flymake`](https://github.com/doomemacs/doomemacs/pull/6660). However, this is not part of the [latest docs](https://github.com/doomemacs/doomemacs/blob/master/docs/modules.org#checkers) which is why I did not configure this initially. I've added the `+flymake` flag and now `flymake` is running as expected (with `flycheck` being disabled). The only issue that remains is that the `ruff` diagnostics only show up after calling `revert-buffer`. Upon opening a new file, only `eglot`'s `basedpyright` diagnostics are shown.

To be clear, the current `doom` setup consists of:

## Current Doom config

`init.el`:
```elisp
:tools
(lsp +eglot)

:checkers
(syntax +flymake)
```
`packages.el`:
```elisp
(package! flymake-ruff)
```
`config.el`:
```elisp
(use-package! flymake-ruff
  :hook (eglot-managed-mode . flymake-ruff-load))

(defun my-filter-eglot-diagnostics (diags)
    "Drop Pyright 'variable not accessed' notes from DIAGS."
    (list (seq-remove (lambda (d)
                        (and (eq (flymake-diagnostic-type d) 'eglot-note)
                             (s-starts-with? "basedpyright" (flymake-diagnostic-text d))
                             (s-ends-with? "is not accessed" (flymake-diagnostic-text d))))
                      (car diags))))

(advice-add 'eglot--report-to-flymake :filter-args #'my-filter-eglot-diagnostics)
```

## Output
> Hi, can you check these things?
> 
> * `C-h m` and check if `flymake` is enabled

It is now enabled (wasn't before).
> * `M :` (eval expression) and type `(flymake-running-backends)` and share the output

```elisp
(eglot-flymake-backend)
```
after `(revert-buffer)`
```elisp
(eglot-flymake-backend flymake-ruff--run-checker)
```

> * `M :` and type `(executable-find "ruff")` and share the output

```shell
"/home/pelling/.local/bin/ruff"
```

**Comment by erickgnavar** [comment] 2025-10-06 00:05
Can you try something like this?

```emacs-lisp
(use-package python-ts-mode
  :ensure nil
  :hook (python-ts-mode . flymake-ruff-load))
```

This way `flymake` will be enabled based on `python-ts-mode` instead of `eglot`. I think `hook` using `eglot-managed-code` might be the problem 🤔

**Comment by smalltimer** [comment] 2026-03-29 17:28
Hi, I am facing the same! My config is 

```(use-package flymake-ruff
  :straight t
  :hook (eglot-managed-mode . flymake-ruff-load)
  ;; :hook ((python-mode python-ts-mode) . flymake-ruff-load)
  :config
  (setq flymake-ruff-program-args `("--config" ,+v/path-global-pyproject)))
```
I am using ruff 0.15.8 and emacs 30.1. I don't want to move to basedpyright QQ

EDIT: I get the following with `(flymake-running-backends)` :

``` Running backends: eglot-flymake-backend, flymake-ruff--run-checker```
